#!/system/bin/sh
hex_addr=`cat /proc/sys/net/ipv4/debug_ip_filter_dst_ip | awk '{printf("%08X\n", $0)}'`
digital_addr="0x`echo $hex_addr | cut -c 1-2`.0x`echo $hex_addr | cut -c 3-4`.0x`echo $hex_addr | cut -c 5-6`.0x`echo $hex_addr | cut -c 7-8`"
echo $digital_addr  | awk -F . '{printf("%d.%d.%d.%d\n", $1, $2, $3, $4)}'